### ISSUE TITLE
gitignore IDE files

### ISSUE THREAD

**Issue by Tipaa** [Karloski/simorion#2]
Edit the .gitignore file to also ignore IDE related files, such as Eclipse project files or Netbeans config files so we don't mess each other's up with every commit

**Comment by Tipaa** [comment]
(Test issue - Edmund)

**Comment by Karloski** [comment]
This has been done. Feel free to review - I just committed it without doing a pull request as it seemed pointless.

**Comment by Tipaa** [comment]
Looks good
