### ISSUE TITLE
Sprint 1 Goal: Working GUI

### ISSUE THREAD

**Issue by Tipaa** [Karloski/simorion#3]
For the first sprint goal, the GUI should be up and working, with correct modes (performance, on/off, change velocity etc.) and interactions with the underlying device simulation. The actual device simulation will be done later, so for now we can use a mock object instead.

Ideally, we'd start off by just defining the interfaces between everyone's code, like defining the borders to our metaphorical kingdoms. This way, we are decoupled from one another's internal code and have a well-defined reference point.

The work needing to be done:

Swing or JavaFX GUI, choice depending on devs.
Will receive data/instructions only via the View interface, to ensure decoupling of GUI implementation and View (e.g. to allow swapping Swing for JavaFX or HTML at a later date while keeping the same device layout).
Responsible for defining the ViewListener(/GuiListener/Controller/another name) interface, which will be used to relay GUI onClick etc. events to; will only send data/instructions over the ViewListener interface, again for decoupling (e.g. a new device mode is added at a later date).
Completion criteria: ViewListener defined, GUI draws correctly for any View, GUI fires correct events on interaction with user

Controllers, implementing the different Device Mode classes (e.g. performance mode, on/off mode).
Will receive events only via the ViewListener interface, so that the Controller does not depend on the particular GUI library.
Responsible for defining the Model interface, which will be used to relay updates to the internal device simulation/model.
It also needs a way to give a Model access to its coupled Controller View, e.g. controller.getView()
Completion criteria: Model interface defined, Every device mode can accept input events, and can appropriately update the Model

Controller Views, implementing the View interface for each Controller type.
Will have full access to the internal implementations of each Device Mode Controller class, so is tightly coupled. This will require lots of communication between Controller and Controller Views devs.
Will only send data across the View interface, to ensure decoupling of Mode Views and GUI system.
Completion criteria: a View implemented for every mode, correctly telling the GUI what to draw from the Model

Model Dummy, implementing the Model interface.
This class will be fleshed out in the future, so for now it only needs to operate partially (enough to close the GUI loop).
It will implement the Model interface, and only receive instructions/data this way.
Responsible for defining the View interface, and will only send data/instructions over the View.
Completion criteria: View interface defined, enough of the Model interface is implemented to respond to user inputs (e.g. changeVoice can be a no-op, but changeMode must update the View)

Support Code, filling in the gaps. Probably a part-time role, since there aren't yet many gaps to fill.
Working on filling in the gaps, e.g. creating mock (or possible actual) classes for common types, such as notes, voices, timers or utilities.
Completion criteria: Interfaces are well defined, data transfer types are well defined (e.g. don't just use int arrays to represent rows/voices/whathaveyou) and consistent (e.g. ensure that rows of cells are represented consistently across all interfaces)

Who'd like what?

**Comment by Karloski** [comment]
I'll look at the controller views and thus the view interface. I'm presuming this method would require a single View interface, with many mode classes implementing that interface (i.e., one for each mode). Apologies if this is obvious and/or you stated it, just want to be clear in my mind what the goal is.

**Comment by Karloski** [comment]
I'm still not 100% sure how exactly these are all separated, so I have just put some methods in the View interface in the View branch. You can let me know how wide of the mark I am with a review :P.

**Comment by Tipaa** [comment]
Complete! Dave seems to approve of our MVC, and we are about feature-complete in GUI.
